### ISSUE TITLE
[lex] token's column has wrong value

### ISSUE THREAD

**Issue by zeroFruit** [DE-labtory/koa#205]
**Where**
lexer

**Bug detail**
token's `column` has wrong value

**Comment by joomanzi** [comment]
In lexer, lex access column only through cut function. it depends on s.end value. 
so if if bug exist, i guess it might be on next function or backup. i would check further

**Comment by joomanzi** [comment]
in next function
```
func (s *state) next() rune {
	if int(s.end) >= len(s.input) {
		s.width = 0
		return eof
	}

	r, w := utf8.DecodeRuneInString(s.input[s.end:])
	s.width = Pos(w)
	s.end += s.width

	if r == '\n' {
		s.line++
	}
	return r
}
```
when rune is '\n', it supposed to init its end, but it doesn't.

The problem @zeroFruit  found is in case of input stream is
```
hello'\n' world  
```
then 'w' should get 0 for column value, but we set 6 instead.  in this case, we see code as a stream.
however, as we design column value for user-friendly debug mod so that 0 is sounds right to me.

so i thought  we supposed to change this s.end value to something else.
```
func (s *state) cut(t TokenType) Token {
	token := Token{t, s.input[s.start:s.end], s.end, s.line}
	s.start = s.end

	return token
}
```

**Comment by joomanzi** [comment]
my suggestion is like this
```
type state struct {
	input      string
	start      Pos
	end        Pos
	line       int
	width      Pos
	insertSemi bool //if true, insert semicolon
        pointer1 Pos // for current column in a line
        pointer2 Pos // for backup function. in case of '\n' we need to store pos
}
